server:
  port: 8082
  context-path: /demo
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ccl?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 123456
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.imooc.demo.entity